// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3YStPfUBWSWUoEwO3M63cUJkeWbp-eE',
    appId: '1:406983759460:web:bfa06542bf9076b83cb171',
    messagingSenderId: '406983759460',
    projectId: 'notes-c4a0e',
    authDomain: 'notes-c4a0e.firebaseapp.com',
    storageBucket: 'notes-c4a0e.firebasestorage.app',
    measurementId: 'G-PYSL3PS1SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpcDkFCNG-9gw_0bOMXncqYYYlgGQOx8',
    appId: '1:406983759460:android:d086a6d515a002083cb171',
    messagingSenderId: '406983759460',
    projectId: 'notes-c4a0e',
    storageBucket: 'notes-c4a0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5By8Md2_8HFB11yCAAJosxiWSg7lW3I8',
    appId: '1:406983759460:ios:40f57e6b41aee0513cb171',
    messagingSenderId: '406983759460',
    projectId: 'notes-c4a0e',
    storageBucket: 'notes-c4a0e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5By8Md2_8HFB11yCAAJosxiWSg7lW3I8',
    appId: '1:406983759460:ios:40f57e6b41aee0513cb171',
    messagingSenderId: '406983759460',
    projectId: 'notes-c4a0e',
    storageBucket: 'notes-c4a0e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );
}
